package exception;

public class error2 {

	public static void main(String[] args) throws vikram{
		// TODO Auto-generated method stub

		try {
			throw new vikram();
		} catch (vikram e) {
			// TODO Auto-generated catch block
			System.out.println(e);
		}
	}
}
